name: Daily Data Sync

on:
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run data sync
      run: |
        python scripts/sync_data.py --batch --verbose
        
    - name: Check sync results
      run: |
        python -c "
        from app.data.last_update import get_data_summary
        summary = get_data_summary()
        print(f'Total records: {summary[\"total_records\"]}')
        print(f'Successful: {summary[\"successful_records\"]}')
        print(f'Failed: {summary[\"failed_records\"]}')
        print(f'Fresh data: {summary[\"fresh_data\"]}')
        print(f'Stale data: {summary[\"stale_data\"]}')
        
        if summary['failed_records'] > 0:
            print('❌ Some sync operations failed')
            exit(1)
        else:
            print('✅ All sync operations successful')
        "
        
    - name: Upload logs (if sync fails)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: sync-logs
        path: logs/






