name: Weekly Backtest

on:
  schedule:
    # Run every Monday at 2:00 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  backtest:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create necessary directories
      run: |
        mkdir -p storage logs reports
    
    - name: Fetch latest data
      run: |
        python examples/example_fetch_data.py
      continue-on-error: true
    
    - name: Run comprehensive backtest
      run: |
        python examples/example_backtest_complete.py > reports/weekly_backtest_$(date +%Y%m%d).txt
      continue-on-error: true
    
    - name: Upload backtest reports
      uses: actions/upload-artifact@v3
      with:
        name: backtest-reports
        path: reports/
        retention-days: 30

